### ISSUE TITLE
EnterpriseNumber regex pattern allows values starting with |

### ISSUE THREAD

**Issue by jpraet** [belgif/openapi-organization-identifier#3]
```yaml
pattern: '^[0|1]\d{9}$'
```

should be

```yaml
pattern: '^[0-1]\d{9}$'
```

**Comment by pvdbosch** [comment]
Good catch, fixed on master.

I'll release this as a patch version.
Even though it is technically backwards-incompatible, applications and APIs using this schema are designed under the assumption that the "|" is disallowed.

**Comment by pvdbosch** [comment]
Patch release has been created, will become available on Maven Central when it's re-indexed.
